---
- name: set Kernel Linux map count
  become: true
  command:
    cmd: sysctl -w vm.max_map_count=262144

- name: Ensure SonarQube directory exists
  file:
    path: /opt/sonarqube
    state: directory
    owner: ec2-user
    group: docker

- name: Run PostgreSQL for SonarQube
  docker_container:
    name: sonar-db
    image: postgres:15
    state: started
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar_password
      POSTGRES_DB: sonarqube
    volumes:
      - /opt/sonarqube/data:/var/lib/postgresql/data

- name: Run SonarQube
  docker_container:
    name: sonarqube
    image: sonarqube:community
    state: started
    published_ports:
      - "9000:9000"
    env:
      SONAR_JDBC_URL: "jdbc:postgresql://sonar-db:5432/sonarqube"
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar_password
    links:
      - "sonar-db:sonar-db"

- name: Download Trivy binary
  get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.69.3/trivy_0.69.3_Linux-64bit.tar.gz
    dest: /tmp/trivy.tar.gz

- name: Extract Trivy
  unarchive:
    src: /tmp/trivy.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    include: ["trivy"]
    mode: '0755'

- name: Install Node.js
  dnf:
    name: nodejs
    state: present

- name: Install Snyk CLI globally
  npm:
    name: snyk
    global: yes

- name: Install AWS CLI
  dnf:
    name: awscli
    state: present

- name: Install snyk-to-html utility
  npm:
    name: snyk-to-html
    global: yes

- name: Create reports directory
  file:
    path: /home/ec2-user/reports
    state: directory
    owner: ec2-user
    group: ec2-user