---
- name: Create prometheus group
  become: true
  group:
    name: prometheus
    system: yes

- name: Create prometheus user
  become: true
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin

- name: Create /etc/prometheus
  become: true
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create /var/lib/prometheus
  become: true
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Download Prometheus
  become: true
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  become: true
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus binary
  become: true
  copy:
    src: /tmp/prometheus-3.10.0.linux-amd64/prometheus
    dest: /usr/local/bin/
    remote_src: true
    mode: '0755'

- name: Copy promtool
  become: true
  copy:
    src: /tmp/prometheus-3.10.0.linux-amd64/promtool
    dest: /usr/local/bin/
    remote_src: true
    mode: '0755'

- name: Copy prometheus config
  become: true
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'

- name: Create systemd file
  become: true
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

#TO DO: auto config prometheus for all node

######## GRAFANA ##########

- name: Create repo folder
  become: true
  file:
    path: /etc/yum.repos.d/
    state: directory
    mode: '0755'

- name: Create repo grafana
  become: true
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo

- name: Update repo
  become: true
  dnf:
    name: "*"
    state: latest
    update_only: yes

- name: Install grafana
  become: true
  dnf:
    name: grafana

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Start service grafana
  become: true
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Start Prometheus
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Check Prometheus status
  become: true
  systemd:
    name: prometheus
  register: Prometheus_status

- name: Check grafana status
  become: true
  systemd:
    name: grafana-server
  register: Grafana_status

- name: Show grafana status
  debug:
    msg: "Grafana service status: {{ Grafana_status.status.ActiveState }}"

- name: Show Prometheus service status
  debug:
    msg: "Prometheus service status: {{ Prometheus_status.status.ActiveState }}"

- name: Show Prometheus config instruction
  debug:
    msg: |
      ===== NEXT STEP: CONFIG PROMETHEUS =====

      1. Edit file:
         sudo nano /etc/prometheus/prometheus.yml

      2. Add Node Exporter target:

      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]

        - job_name: "node_exporter"
          static_configs:
            - targets: ["localhost:9100"]

      3. Restart Prometheus:
         sudo systemctl restart prometheus

      ========================================