pipeline {
    agent none
    environment {
        BUID_TAG="v${BUILD_NUMBER}"
        S3_URL = "s3://devsecops-reports-haridtvt/${JOB_NAME}/${BUILD_TAG}/"
    }
    stages {
        stage('Check out') {
            agent {
                label 'Security_node || Jenkins_node || Application_node'
            }
            steps {
                checkout scm
            }
        }
        stage('Scan code with snyk and sonarqube') {
            agent { label 'Security_node' }
            environment {
                // Lấy token từ Jenkins Credentials
                SONAR_AUTH_TOKEN = credentials('Sonarqube_token')
                SNYK_TOKEN = credentials('Snyk_credentials')
                SONAR_URL = "http://localhost:9000"
            }
            steps {
                sh 'snyk code test --json | snyk-to-html -o report-code.html || true'
                sh 'snyk iac test --json | snyk-to-html -o report-iac.html || true'
                sh 'aws s3 cp report-code.html ${S3_URL}'
                sh 'aws s3 cp report-iac.html ${S3_URL}'
                sh 'rm -rf report-code.html report-iac.html'
                sh """
                    docker run --rm \
                        --network host \
                        -e SONAR_HOST_URL="${SONAR_URL}" \
                        -e SONAR_TOKEN="${SONAR_AUTH_TOKEN}" \
                        -v "${WORKSPACE}:/usr/src" \
                        sonarsource/sonar-scanner-cli \
                        -Dsonar.projectKey=my-devsecops-project \
                        -Dsonar.sources=.
                """
            }
        }
//        state('Build and Images scan') {
//            agent { label 'security_node' }
//            steps {
//                script {
//                    withCredentials([usernamePassword(credentialsId: '', usernameVariable: 'DOCKER_UNAME', passwordVariable: 'DOCKER_PASS')]) {
//                        sh "echo ${DOCKER_PASS}"
//                        sh "docker build -t ${DOCKER_USER}/application:${BUID_TAG} ./shop-app/ "
//                        // check trivy scan
//                        // acceptance condition
//                        // push report s3
//                        // cleanup
//                    }
//                }
//            }
//        }
//        stage('Deploy') {
//            agent {
//                label 'application_node'
//            }
//            steps {
//                sh 'docker pull ${DOCKER_USER}/application:${BUID_TAG}'
//                sh 'docker-compose up -d'
//            }
//        }
//        post {
//            success {
//                echo 'SUCCESS: Backend deployed successfully.'
//            }
//            failure {
//                echo 'FAILURE: Deployment failed. Please check the logs.'
//            }
//        }
    }
}